name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  coding-standards:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '8.3'
        dependencies:
          - 'highest'

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install lowest dependencies
        if: matrix.dependencies == 'lowest'
        run: composer update --prefer-dist --prefer-lowest --no-progress

      - name: Install locked dependencies
        if: matrix.dependencies == 'locked'
        run: composer install --prefer-dist --no-progress

      - name: Install highest dependencies
        if: matrix.dependencies == 'highest'
        run: composer update --prefer-dist --no-progress

      - name: Check coding standards
        run: composer run-script test:cs

  static-code-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '8.3'
        dependencies:
          - 'highest'

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install lowest dependencies
        if: matrix.dependencies == 'lowest'
        run: composer update --prefer-dist --prefer-lowest --no-progress

      - name: Install locked dependencies
        if: matrix.dependencies == 'locked'
        run: composer install --prefer-dist --no-progress

      - name: Install highest dependencies
        if: matrix.dependencies == 'highest'
        run: composer update --prefer-dist --no-progress

      - name: Run static code analysis
        run: composer run-script test:phpstan

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.3'
          - '8.4'
          - '8.5'
        dependencies:
          - 'highest'

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dcb
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dcb
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo_mysql, pdo_sqlite, pdo_pgsql

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install lowest dependencies
        if: matrix.dependencies == 'lowest'
        run: composer update --prefer-dist --prefer-lowest --no-progress

      - name: Install locked dependencies
        if: matrix.dependencies == 'locked'
        run: composer install --prefer-dist --no-progress

      - name: Install highest dependencies
        if: matrix.dependencies == 'highest'
        run: composer update --prefer-dist --no-progress

      - name: Run tests (SQLite)
        run: composer run-script test:integration
        env:
          DCB_TEST_DSN: "pdo-sqlite:///events.sqlite"

      - name: Run tests (MySQL)
        run: composer run-script test:integration
        env:
          DCB_TEST_DSN: "pdo-mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/dcb"

      - name: Run tests (PostgreSQL)
        run: composer run-script test:integration
        env:
          DCB_TEST_DSN: "pdo-pgsql://root:password@127.0.0.1:${{ job.services.postgres.ports['5432'] }}/dcb"

      - name: Run consistency tests (SQLite)
        run: composer run-script test:consistency
        env:
          DCB_TEST_DSN: "pdo-sqlite:///events.sqlite"

      - name: Run consistency tests (MySQL)
        run: composer run-script test:consistency
        env:
          DCB_TEST_DSN: "pdo-mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/dcb"

      - name: Run consistency tests (PostgreSQL)
        run: composer run-script test:consistency
        env:
          DCB_TEST_DSN: "pdo-pgsql://root:password@127.0.0.1:${{ job.services.postgres.ports['5432'] }}/dcb"
