name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.4'
        dependencies:
          - 'lowest'
          - 'highest'
        database:
          - image: 'mysql:8.0'
            port: '3307:3306'
            dsn: 'pdo-mysql://root:password@127.0.0.1:3307/dcb'
            health-cmd: 'mysqladmin ping'
            extension: 'pdo_mysql'
          - image: 'mysql:8.4'
            port: '3307:3306'
            dsn: 'pdo-mysql://root:password@127.0.0.1:3307/dcb'
            health-cmd: 'mysqladmin ping'
            extension: 'pdo_mysql'
          - image: 'mariadb:10.11'
            port: '3307:3306'
            dsn: 'pdo-mysql://root:password@127.0.0.1:3307/dcb'
            health-cmd: 'mariadb-admin ping'
            extension: 'pdo_mysql'
          - image: 'mariadb:11.4'
            port: '3307:3306'
            dsn: 'pdo-mysql://root:password@127.0.0.1:3307/dcb'
            health-cmd: 'mariadb-admin ping'
            extension: 'pdo_mysql'
          - image: 'postgres:16'
            port: '5432:5432'
            dsn: 'pdo-pgsql://postgres:password@127.0.0.1:5432/dcb'
            health-cmd: 'pg_isready'
            extension: 'pdo_pgsql'
          - image: 'postgres:17'
            port: '5432:5432'
            dsn: 'pdo-pgsql://postgres:password@127.0.0.1:5432/dcb'
            health-cmd: 'pg_isready'
            extension: 'pdo_pgsql'

    services:
      database:
        image: ${{ matrix.database.image }}
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dcb
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: dcb
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dcb
        ports:
          - ${{ matrix.database.port }}
        options: >-
          --health-cmd="${{ matrix.database.health-cmd }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ matrix.database.extension }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install lowest dependencies
        if: matrix.dependencies == 'lowest'
        run: composer update --prefer-dist --prefer-lowest --no-progress

      - name: Install locked dependencies
        if: matrix.dependencies == 'locked'
        run: composer install --prefer-dist --no-progress

      - name: Install highest dependencies
        if: matrix.dependencies == 'highest'
        run: composer update --prefer-dist --no-progress

      - name: Set DSN
        run: echo "DCB_TEST_DSN=${{ matrix.database.dsn }}" >> $GITHUB_ENV

      - name: Run integration tests
        run: composer run-script test:integration

      - name: Run consistency tests
        run: composer run-script test:consistency

  tests-default-db:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.4'
        dependencies:
          - 'lowest'
          - 'highest'

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo_sqlite

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install lowest dependencies
        if: matrix.dependencies == 'lowest'
        run: composer update --prefer-dist --prefer-lowest --no-progress

      - name: Install locked dependencies
        if: matrix.dependencies == 'locked'
        run: composer install --prefer-dist --no-progress

      - name: Install highest dependencies
        if: matrix.dependencies == 'highest'
        run: composer update --prefer-dist --no-progress

      - name: Run integration tests
        run: composer run-script test:integration

      - name: Run consistency tests
        run: composer run-script test:consistency
